source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'JFMeiTuan_Swift' do
    pod 'SnapKit', '~> 3.2.0'
    pod 'SwiftyJSON', '~> 4.0.0'
    pod 'ObjectMapper', '~> 2.2'
    pod 'Alamofire', '~> 4.4'
    pod 'IQKeyboardManagerSwift', '~> 5.0.7'
    pod 'NVActivityIndicatorView', '~> 4.1.1'
    pod 'PagingMenuController', '~> 2.2.0'
    pod 'Kingfisher', '~> 4.6.3'
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'SwiftyGif', '~> 4.1.0'
end
