source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'JFMeiTuan_Swift' do
    pod 'SnapKit', '~> 3.2.0'
    pod 'SwiftyJSON'
    pod 'ObjectMapper', '~> 2.2'
    pod 'Alamofire', '~> 4.4'
end
